"""Toolbox Globe Tools"""
__all__ = ['ManageGlobeServerCacheTiles_globe', 'DeleteGlobeServerCache_globe']
from arcpy.geoprocessing._base import gptooldoc, gp, gp_fixargs
from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

# Server Tools toolset
@gptooldoc('DeleteGlobeServerCache_globe', None)
def DeleteGlobeServerCache_globe(server_name=None, object_name=None, Layer=None):
    """DeleteGlobeServerCache_globe(server_name, object_name, Layer;Layer...)

    Deletes an existing Globe Service layer's cache.
    This is an unrecoverable operation so only use if you are sure you no longer need the cache.


      INPUTS:
      server_name (String): The host name of the ArcGIS Server to use to update the cache.
      object_name (String): The name of the Globe Service to use to update the cache.
      Layer (String): Update the data cache of the chosen layers. All layers of the service are checked by default. If a layer is unchecked the layers cache will not be deleted."""
    try:
        return convertArcObjectToPythonObject(gp.DeleteGlobeServerCache_globe(*gp_fixargs((server_name, object_name, Layer), True)))
    except Exception, e:
        raise e

@gptooldoc('ManageGlobeServerCacheTiles_globe', None)
def ManageGlobeServerCacheTiles_globe(server_name=None, object_name=None, in_layers=None, update_mode=None, update_extent=None, thread_count=None, update_feature_class=None, ignore_status=None):
    """ManageGlobeServerCacheTiles_globe(server_name, object_name, in_layers;in_layers..., None|Recreate Empty Tiles|Recreate All Tiles, {update_extent}, {thread_count}, {update_feature_class}, {IGNORE_COMPLETION_STATUS_FIELD|TRACK_COMPLETION_STATUS})

    Creates and updates tiles in an existing Globe Service cache. This tool is used to create new tiles or to replace missing tiles, overwrite outdated tiles, or add new tiles in new areas by specific extents or by using a polygon feature class to generate tiles by feature extents.
    There are two modes of operation: Recreate Empty Tiles-Only tiles that are empty (have been deleted on disk), or that are new because the cache extent has changed or because new layers have been added to the globe service, will be created. Existing tiles will be left unchanged. Recreate All Tiles-All tiles, including existing tiles, will be replaced. Additionally new tiles will be added if a layers data extent has changed or new layers have been added to the globe service.
    New Features This tool has the following new features at version 9.3: Ability to generate data cache for feature data as vectors. This means now all globe supported data types can have their data cache generated by the server. Redesigned to allow you to specify the data caching levels for each layer in the service. Ability to cache specific extents using a feature class and track cache completion status for each feature. A better user experience.


      INPUTS:
      server_name (String): The host name of the ArcGIS Server Server Object Manager (SOM) that will be used to generate the cache.
      object_name (String): The name of the GlobeServer configuration that will be used to generate the cache.
      in_layers (Value Table): Choose an area of the layer for which the cache should be updated. You can do so by specifying the extent values or choosing an extent from an existing data source. Choosing a new cache extent will update tiles in every level of detail that intersects that extent.
      update_mode (String): Select the layers to include in the layer cache.
      update_extent {Extent}: Select the level-of-detail scale you would like to begin caching the layer. If the smallest and largest level-of-detail scales are used for the minimum and maximum, a full cache will be built for the layer.
      thread_count {Long}: Select the level-of-detail scale you would like to begin caching the layer. If the smallest and largest level-of-detail scales are used for the minimum and maximum, a full cache will be built for the layer.
      update_feature_class {Feature Class}: The specified number of threads to attempt to create on the client. Each thread, in turn, will try to create a server context on the globe server object to generate the cache.
      ignore_status {Boolean}: Choose a mode for updating the cache. The two modes are: Recreate Empty TilesOnly tiles that are empty (have been deleted on disk), or that are new because the cache extent has changed or because new layers have been added to the globe service, will be created.  Existing tiles will be left unchanged. Recreate All TilesAll tiles, including existing tiles, will be replaced. Additionally new tiles will be added if a layers data extent has changed or new layers have been added to the globe service."""
    try:
        return convertArcObjectToPythonObject(gp.ManageGlobeServerCacheTiles_globe(*gp_fixargs((server_name, object_name, in_layers, update_mode, update_extent, thread_count, update_feature_class, ignore_status), True)))
    except Exception, e:
        raise e

